name: test

on:
  push:
    branches:    
      - main

jobs:
  gcloud:
    name: test-gcloud-action-in-new-org-this-should-continue-working
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bharathkkb-org-2/setup-gcloud/setup-gcloud@master # Set up ADC for credentials
